"""Add needs_admin_approval

Revision ID: bfe3c8ae8e11
Revises: 7be96a8c89b8
Create Date: 2026-04-30 22:03:48.650217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfe3c8ae8e11'
down_revision: Union[str, None] = '7be96a8c89b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('needs_admin_approval', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'needs_admin_approval')
    # ### end Alembic commands ###
